### ISSUE TITLE
Support updating the list of gltf scenes without re-compiling the player

### ISSUE THREAD

**Issue by Etiennefaivredarcier** [5G-MAG/rt-xr-unity-player#32]
To create a ‘paths.txt’ file that can contains multiple glTF file paths, so the application doesn’t need to be compiled with embedded paths. Each path should creates a button loading the associated glTF file.

**Comment by Etiennefaivredarcier** [comment]
This system should support local file paths, but also remote ones

**Comment by nlsdvl** [comment]
The Paths.txt is implemented and supports http URLs.

However I was not able to edit or update `Paths.txt` on the Android device at the application persistent data path.
I made changes to load the file from `/Assets/Ressources` a compile time dependency. I am closing the

The ticket will be closed when I roll back the change and documentation covers updating the Paths.txt file on the Android device.
