### ISSUE TITLE
3D scene doesn't follow the 2D AR marker when the marker is rotated and moved around

### ISSUE THREAD

**Issue by nlsdvl** [5G-MAG/rt-xr-unity-player#44]
After marker is detected, 3D object is anchored to initial marker position, when moving the marker around, the object doesn't follow. On apk compiled using Unity LTS (2021 & 2022).

cc @Etiennefaivredarcier

**Comment by Etiennefaivredarcier** [comment]
Fixed this by updating the glTFast repo on this branch: https://github.com/5G-MAG/rt-xr-gITFast/tree/rt-xr/bug-fix-unity-player-44
